"""
calculator.py
-------------
Physics-first CO2 emissions calculator for EV vs ICE comparison.

Design philosophy
-----------------
The core savings figure is always computed deterministically from official
emission factors — no machine learning required for the base case. The XGBoost
model in model.py provides an optional real-world adjustment factor that
accounts for conditions that deviate from the WLTP test cycle (temperature,
driving style, battery age).

All emission factors come from config.py, which cites DCCEEW 2023 sources.
"""

from __future__ import annotations
from dataclasses import dataclass, field

from src.config import (
    GRID_EMISSION_FACTORS,
    FUEL_EMISSION_FACTORS,
    FUEL_TYPE_ALIASES,
    BATTERY_MANUFACTURING_KG_CO2_PER_KWH,
    EV_ASSEMBLY_OVERHEAD_KG_CO2,
    BATTERY_EOL_CREDIT_KG_CO2,
    DEFAULT_ANNUAL_KM,
    DEFAULT_VEHICLE_LIFETIME_YEARS,
    ELECTRICITY_PRICE_AUD_PER_KWH,
    FUEL_PRICES_AUD_PER_L,
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _resolve_fuel_type(fuel_type: str) -> str:
    """Normalise user-supplied fuel type strings to a canonical key."""
    key = fuel_type.strip().lower()
    canonical = FUEL_TYPE_ALIASES.get(key)
    if canonical is None:
        # Try direct match (case-insensitive) against known keys
        for k in FUEL_EMISSION_FACTORS:
            if k.lower() == key:
                return k
        raise ValueError(
            f"Unknown fuel type '{fuel_type}'. "
            f"Valid values: {list(FUEL_EMISSION_FACTORS.keys())}"
        )
    return canonical


def _resolve_state(state: str) -> str:
    """Validate and normalise Australian state code."""
    s = state.strip().upper()
    if s not in GRID_EMISSION_FACTORS:
        raise ValueError(
            f"Unknown state '{state}'. "
            f"Valid values: {list(GRID_EMISSION_FACTORS.keys())}"
        )
    return s


# ---------------------------------------------------------------------------
# Core calculation functions
# ---------------------------------------------------------------------------

def ev_co2_g_per_km(
    consumption_kwh_per_100km: float,
    state: str,
    real_world_adjustment: float = 1.0,
) -> float:
    """
    Calculate EV CO2 emissions in grams per kilometre.

    Parameters
    ----------
    consumption_kwh_per_100km : float
        WLTP energy consumption (kWh drawn from the AC socket per 100 km).
    state : str
        Australian state code (e.g. 'NSW'). Determines grid intensity.
    real_world_adjustment : float
        Multiplier to convert WLTP to real-world consumption.
        1.0 = use WLTP as-is. Values > 1 mean real-world is worse than WLTP.
        Generated by the XGBoost model; defaults to 1.0 (WLTP-only mode).

    Returns
    -------
    float
        Grams of CO2-equivalent emitted per kilometre driven.

    Formula
    -------
    EV_gCO2/km = (kWh/100km × adjustment / 100) × grid_kg_CO2/kWh × 1000 g/kg
               = kWh/100km × adjustment × grid_kg_CO2/kWh × 10
    """
    state = _resolve_state(state)
    grid_kg_per_kwh = GRID_EMISSION_FACTORS[state]
    real_world_kwh_per_100km = consumption_kwh_per_100km * real_world_adjustment
    return real_world_kwh_per_100km * grid_kg_per_kwh * 10.0


def ice_co2_g_per_km(
    consumption_l_per_100km: float,
    fuel_type: str,
) -> float:
    """
    Calculate ICE vehicle CO2 emissions in grams per kilometre.

    Parameters
    ----------
    consumption_l_per_100km : float
        WLTP combined fuel consumption in litres per 100 km.
    fuel_type : str
        Fuel type key (e.g. 'Petrol', 'Diesel').

    Returns
    -------
    float
        Grams of CO2-equivalent emitted per kilometre driven.

    Formula
    -------
    ICE_gCO2/km = (L/100km / 100) × emission_factor_kg/L × 1000 g/kg
                = L/100km × emission_factor_kg/L × 10
    """
    fuel_type = _resolve_fuel_type(fuel_type)
    emission_factor_kg_per_l = FUEL_EMISSION_FACTORS[fuel_type]
    return consumption_l_per_100km * emission_factor_kg_per_l * 10.0


def manufacturing_co2_g_per_km(
    battery_kwh: float,
    lifetime_km: float,
    include_eol_credit: bool = True,
) -> float:
    """
    Amortise battery manufacturing CO2 over the vehicle's lifetime.

    Parameters
    ----------
    battery_kwh : float
        Usable battery capacity in kWh.
    lifetime_km : float
        Total expected kilometres driven over the vehicle's life.
    include_eol_credit : bool
        If True, subtract a credit for battery second-life / recycling.

    Returns
    -------
    float
        Grams of CO2 per kilometre (lifecycle overhead).
    """
    total_kg = (
        battery_kwh * BATTERY_MANUFACTURING_KG_CO2_PER_KWH
        + EV_ASSEMBLY_OVERHEAD_KG_CO2
    )
    if include_eol_credit:
        total_kg -= BATTERY_EOL_CREDIT_KG_CO2

    total_g = max(total_kg, 0) * 1000
    return total_g / max(lifetime_km, 1)


# ---------------------------------------------------------------------------
# Rich result dataclass
# ---------------------------------------------------------------------------

@dataclass
class EmissionsResult:
    # --- EV figures ---
    ev_wltp_consumption_kwh_per_100km: float
    ev_real_world_consumption_kwh_per_100km: float
    ev_grid_intensity_g_per_kwh: float
    ev_tailpipe_g_per_km: float          # always 0 for pure EV
    ev_operational_g_per_km: float       # from grid electricity
    ev_manufacturing_g_per_km: float     # amortised lifecycle
    ev_total_g_per_km: float             # operational + manufacturing

    # --- ICE figures ---
    ice_consumption_l_per_100km: float
    ice_fuel_type: str
    ice_emission_factor_g_per_l: float
    ice_operational_g_per_km: float

    # --- Comparison ---
    co2_savings_g_per_km: float          # positive = EV is cleaner
    co2_savings_kg_per_year: float
    co2_savings_tonnes_lifetime: float
    percentage_reduction: float          # relative to ICE

    # --- Real-world adjustment ---
    real_world_adjustment_factor: float
    state: str

    # --- Driving parameters ---
    annual_km: float
    vehicle_lifetime_years: float
    driving_style: str
    include_lifecycle: bool

    # --- Financial ---
    ev_cost_aud_per_km: float
    ice_cost_aud_per_km: float
    cost_saving_aud_per_km: float
    cost_saving_aud_per_year: float
    cost_saving_aud_lifetime: float

    # --- Equivalents (for UX display) ---
    trees_planted_equivalent_per_year: int
    petrol_litres_saved_per_year: float


# ---------------------------------------------------------------------------
# Main calculation entry point
# ---------------------------------------------------------------------------

def calculate(
    ev_consumption_kwh_per_100km: float,
    ev_battery_kwh: float,
    ice_consumption_l_per_100km: float,
    ice_fuel_type: str,
    state: str,
    real_world_adjustment: float = 1.0,
    annual_km: float = DEFAULT_ANNUAL_KM,
    vehicle_lifetime_years: float = DEFAULT_VEHICLE_LIFETIME_YEARS,
    driving_style: str = "mixed",
    include_lifecycle: bool = True,
) -> EmissionsResult:
    """
    Full EV vs ICE CO2 comparison with optional lifecycle emissions.

    Parameters
    ----------
    ev_consumption_kwh_per_100km : float
        WLTP AC energy consumption of the EV.
    ev_battery_kwh : float
        Usable battery capacity (kWh). Used for lifecycle calculation.
    ice_consumption_l_per_100km : float
        WLTP combined fuel consumption of the ICE vehicle.
    ice_fuel_type : str
        Fuel type of the ICE vehicle.
    state : str
        Australian state code for grid intensity.
    real_world_adjustment : float
        Multiplier for real-world EV consumption vs WLTP (default 1.0).
    annual_km : float
        Expected annual driving distance.
    vehicle_lifetime_years : float
        Expected vehicle ownership/lifetime.
    driving_style : str
        'city', 'mixed', or 'highway'. Informational; use model.py to derive
        the real_world_adjustment from this.
    include_lifecycle : bool
        Whether to add battery manufacturing emissions to EV total.

    Returns
    -------
    EmissionsResult
        Fully populated result dataclass.
    """
    state = _resolve_state(state)
    ice_fuel_type = _resolve_fuel_type(ice_fuel_type)
    lifetime_km = annual_km * vehicle_lifetime_years

    # --- EV emissions ---
    ev_real_world_kwh = ev_consumption_kwh_per_100km * real_world_adjustment
    ev_operational = ev_co2_g_per_km(ev_consumption_kwh_per_100km, state, real_world_adjustment)
    ev_manufacturing = (
        manufacturing_co2_g_per_km(ev_battery_kwh, lifetime_km)
        if include_lifecycle
        else 0.0
    )
    ev_total = ev_operational + ev_manufacturing

    # --- ICE emissions ---
    ice_operational = ice_co2_g_per_km(ice_consumption_l_per_100km, ice_fuel_type)

    # --- Savings ---
    # Savings compares like-for-like: operational only, or with lifecycle on EV side.
    savings_g_km = ice_operational - ev_total
    savings_kg_year = (savings_g_km * annual_km) / 1000
    savings_t_lifetime = (savings_g_km * lifetime_km) / 1_000_000
    pct_reduction = (savings_g_km / ice_operational * 100) if ice_operational > 0 else 0.0

    # --- Financial ---
    ev_cost_per_km = (ev_real_world_kwh / 100) * ELECTRICITY_PRICE_AUD_PER_KWH
    fuel_price = FUEL_PRICES_AUD_PER_L.get(ice_fuel_type, 2.00)
    ice_cost_per_km = (ice_consumption_l_per_100km / 100) * fuel_price
    cost_saving_per_km = ice_cost_per_km - ev_cost_per_km
    cost_saving_per_year = cost_saving_per_km * annual_km
    cost_saving_lifetime = cost_saving_per_km * lifetime_km

    # --- Equivalents ---
    # Trees: 1 mature tree absorbs ~21 kg CO2/year (CSIRO estimate)
    trees = int(max(savings_kg_year, 0) / 21)
    # Petrol saved: how many litres of petrol equivalent
    petrol_ef_g_per_l = FUEL_EMISSION_FACTORS["Petrol"] * 1000
    petrol_litres_saved = max(savings_g_km * annual_km / petrol_ef_g_per_l, 0)

    return EmissionsResult(
        # EV
        ev_wltp_consumption_kwh_per_100km=round(ev_consumption_kwh_per_100km, 2),
        ev_real_world_consumption_kwh_per_100km=round(ev_real_world_kwh, 2),
        ev_grid_intensity_g_per_kwh=round(GRID_EMISSION_FACTORS[state] * 1000, 1),
        ev_tailpipe_g_per_km=0.0,
        ev_operational_g_per_km=round(ev_operational, 2),
        ev_manufacturing_g_per_km=round(ev_manufacturing, 2),
        ev_total_g_per_km=round(ev_total, 2),
        # ICE
        ice_consumption_l_per_100km=round(ice_consumption_l_per_100km, 2),
        ice_fuel_type=ice_fuel_type,
        ice_emission_factor_g_per_l=round(FUEL_EMISSION_FACTORS[ice_fuel_type] * 1000, 1),
        ice_operational_g_per_km=round(ice_operational, 2),
        # Comparison
        co2_savings_g_per_km=round(savings_g_km, 2),
        co2_savings_kg_per_year=round(savings_kg_year, 1),
        co2_savings_tonnes_lifetime=round(savings_t_lifetime, 2),
        percentage_reduction=round(pct_reduction, 1),
        # Adjustment
        real_world_adjustment_factor=round(real_world_adjustment, 4),
        state=state,
        # Usage
        annual_km=annual_km,
        vehicle_lifetime_years=vehicle_lifetime_years,
        driving_style=driving_style,
        include_lifecycle=include_lifecycle,
        # Financial
        ev_cost_aud_per_km=round(ev_cost_per_km, 4),
        ice_cost_aud_per_km=round(ice_cost_per_km, 4),
        cost_saving_aud_per_km=round(cost_saving_per_km, 4),
        cost_saving_aud_per_year=round(cost_saving_per_year, 2),
        cost_saving_aud_lifetime=round(cost_saving_lifetime, 2),
        # Equivalents
        trees_planted_equivalent_per_year=trees,
        petrol_litres_saved_per_year=round(petrol_litres_saved, 1),
    )
