name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build-production:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Login to docker hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{secrets.CI_DOCKER_USERNAME}}
  #         password: ${{secrets.CI_DOCKER_PASSWORD}}

  #     - name: Build the docker image
  #       run: |
  #         ls -la 
  #         docker build . -f Dockerfile -t ${{ secrets.CI_DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }}
      
  #     - name: Push the docker image
  #       run: |
  #         docker push ${{ secrets.CI_DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }}

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST }}
            USER_NAME: ${{ secrets.USER_NAME }}

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}

      - run: mkdir -p ~/.ssh/
      - run: echo "{{ secrets.STAGING_KEY }}" > ~/.ssh/private.key
      - run: chmod 600 ~/.ssh/private.key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          echo "hello done"
          '
