name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # build-production:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Login to docker hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{secrets.CI_DOCKER_USERNAME}}
  #         password: ${{secrets.CI_DOCKER_PASSWORD}}

  #     - name: Build the docker image
  #       run: |
  #         ls -la 
  #         docker build . -f Dockerfile -t ${{ secrets.CI_DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }}
      
  #     - name: Push the docker image
  #       run: |
  #         docker push ${{ secrets.CI_DOCKER_USERNAME }}/${{ secrets.APP_NAME }}:${{ github.sha }}

  deploy-production:
    runs-on: ubuntu-latest
    # needs: build-production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}

      # - name: Deploy to Production
        # run: |
        #   echo "$PRIVATE_KEY" > private_key && chmod 600 private_key;
        #   ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
        #   echo "hello done"
        #   '
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SERVER_PROD_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            pbcopy < ~/.ssh/id_rsa
            
            ls -la
